#pragma once

#include "vytal/defines/core/types.h"

// return codes --------------------------------------------------------- //

typedef enum Renderer_Backend_Result {
    RENDERER_BACKEND_SUCCESS                   = 0,
    RENDERER_BACKEND_ERROR_ALREADY_INITIALIZED = -1,
    RENDERER_BACKEND_ERROR_NOT_INITIALIZED     = -2,
    RENDERER_BACKEND_ERROR_INVALID_PARAM       = -3,
    RENDERER_BACKEND_ERROR_INVALID_BACKEND     = -4,
    RENDERER_BACKEND_ERROR_ALLOCATION_FAILED   = -5,
    RENDERER_BACKEND_ERROR_DEALLOCATION_FAILED = -6,

    // Vulkan-specific
    RENDERER_BACKEND_ERROR_VULKAN_EXTS_FETCH_FAILED                         = -100,
    RENDERER_BACKEND_ERROR_VULKAN_LAYERS_FETCH_FAILED                       = -101,
    RENDERER_BACKEND_ERROR_VULKAN_INSTANCE_CONSTRUCT_FAILED                 = -102,
    RENDERER_BACKEND_ERROR_VULKAN_INSTANCE_DESTRUCT_FAILED                  = -103,
    RENDERER_BACKEND_ERROR_VULKAN_DEBUG_FUNCS_LOAD_FAILED                   = -104,
    RENDERER_BACKEND_ERROR_VULKAN_DEBUG_MSG_CONSTRUCT_FAILED                = -105,
    RENDERER_BACKEND_ERROR_VULKAN_DEBUG_MSG_DESTRUCT_FAILED                 = -106,
    RENDERER_BACKEND_ERROR_VULKAN_SURFACE_CONSTRUCT_FAILED                  = -107,
    RENDERER_BACKEND_ERROR_VULKAN_SURFACE_DESTRUCT_FAILED                   = -108,
    RENDERER_BACKEND_ERROR_VULKAN_GPU_SELECT_FAILED                         = -109,
    RENDERER_BACKEND_ERROR_VULKAN_DEVICE_CONSTRUCT_FAILED                   = -110,
    RENDERER_BACKEND_ERROR_VULKAN_DEVICE_DESTRUCT_FAILED                    = -111,
    RENDERER_BACKEND_ERROR_VULKAN_QUEUE_FAMILIES_SEARCH_FAILED              = -112,
    RENDERER_BACKEND_ERROR_VULKAN_COMMAND_POOL_CONSTRUCT_FAILED             = -113,
    RENDERER_BACKEND_ERROR_VULKAN_COMMAND_POOL_DESTRUCT_FAILED              = -114,
    RENDERER_BACKEND_ERROR_VULKAN_SWAPCHAIN_CONSTRUCT_FAILED                = -115,
    RENDERER_BACKEND_ERROR_VULKAN_SWAPCHAIN_DESTRUCT_FAILED                 = -116,
    RENDERER_BACKEND_ERROR_VULKAN_SWAPCHAIN_IMAGE_VIEWS_CONSTRUCT_FAILED    = -117,
    RENDERER_BACKEND_ERROR_VULKAN_SWAPCHAIN_IMAGE_VIEWS_DESTRUCT_FAILED     = -118,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_IMAGE_VIEW_CONSTRUCT_FAILED       = -119,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_POOLS_CONSTRUCT_FAILED         = -120,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_POOLS_DESTRUCT_FAILED          = -121,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_SET_LAYOUTS_CONSTRUCT_FAILED   = -122,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_SET_LAYOUTS_DESTRUCT_FAILED    = -123,
    RENDERER_BACKEND_ERROR_VULKAN_RENDER_PASS_CONSTRUCT_FAILED              = -124,
    RENDERER_BACKEND_ERROR_VULKAN_RENDER_PASS_DESTRUCT_FAILED               = -125,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_SEARCH_SUPPORTED_FORMAT_FAILED    = -126,
    RENDERER_BACKEND_ERROR_VULKAN_DEPTH_RESOURCES_CONSTRUCT_FAILED          = -127,
    RENDERER_BACKEND_ERROR_VULKAN_DEPTH_RESOURCES_DESTRUCT_FAILED           = -128,
    RENDERER_BACKEND_ERROR_VULKAN_GRAPHICS_PIPELINE_CONSTRUCT_FAILED        = -129,
    RENDERER_BACKEND_ERROR_VULKAN_GRAPHICS_PIPELINE_DESTRUCT_FAILED         = -130,
    RENDERER_BACKEND_ERROR_VULKAN_GRAPHICS_UBOS_CONSTRUCT_FAILED            = -131,
    RENDERER_BACKEND_ERROR_VULKAN_GRAPHICS_UBOS_DESTRUCT_FAILED             = -132,
    RENDERER_BACKEND_ERROR_VULKAN_SYNC_RESOURCES_CONSTRUCT_FAILED           = -133,
    RENDERER_BACKEND_ERROR_VULKAN_SYNC_RESOURCES_DESTRUCT_FAILED            = -134,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_SETS_CONSTRUCT_FAILED          = -135,
    RENDERER_BACKEND_ERROR_VULKAN_DESCRIPTOR_SETS_DESTRUCT_FAILED           = -136,
    RENDERER_BACKEND_ERROR_VULKAN_COMMAND_BUFFERS_ALLOCATE_FAILED           = -137,
    RENDERER_BACKEND_ERROR_VULKAN_COMMAND_BUFFERS_DEALLOCATE_FAILED         = -138,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_IMAGE_CONSTRUCT_FAILED            = -139,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_SEARCH_MEMORY_TYPE_FAILED         = -140,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_BEGIN_SINGLE_TIME_COMMANDS_FAILED = -141,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_END_SINGLE_TIME_COMMANDS_FAILED   = -142,
    RENDERER_BACKEND_ERROR_VULKAN_HELPERS_TRANSITION_IMAGE_LAYOUT_FAILED    = -143,
    RENDERER_BACKEND_ERROR_VULKAN_FRAMEBUFFERS_CONSTRUCT_FAILED             = -144,
    RENDERER_BACKEND_ERROR_VULKAN_FRAMEBUFFERS_DESTRUCT_FAILED              = -145,

} RendererBackendResult;

typedef enum Renderer_Module_Result {
    RENDERER_MODULE_SUCCESS                   = 0,
    RENDERER_MODULE_ERROR_ALREADY_INITIALIZED = -1,
    RENDERER_MODULE_ERROR_NOT_INITIALIZED     = -2,
    RENDERER_MODULE_ERROR_INVALID_PARAM       = -3,
    RENDERER_MODULE_ERROR_ALLOCATION_FAILED   = -4,
    RENDERER_MODULE_ERROR_DEALLOCATION_FAILED = -5,
    RENDERER_MODULE_ERROR_PARSE_FAILED        = -6,
} RendererModuleResult;

// backend -------------------------------------------------------------- //

typedef enum Renderer_Backend_Type {
    RENDERER_BACKEND_VULKAN
} RendererBackendType;

typedef struct Renderer_Backend {
    RendererBackendType _type;
    VoidPtr             _context;

    RendererBackendResult (*_startup)(void);
    RendererBackendResult (*_shutdown)(void);
    RendererBackendResult (*_begin_frame)(void);
    RendererBackendResult (*_end_frame)(void);
    RendererBackendResult (*_render)(void);

    ByteSize _memory_size;
} *RendererBackend;

// buffer --------------------------------------------------------------- //

typedef enum Renderer_Buffer_Type {
    RENDERER_BUFFER_VERTEX,
    RENDERER_BUFFER_INDEX,
    RENDERER_BUFFER_UNIFORM
} RendererBufferType;

typedef struct Renderer_Buffer {
    VoidPtr            _handle;
    ByteSize           _size_bytes;
    RendererBufferType _type;

    ByteSize _memory_size;
} *RendererBuffer;

// graphics pipeline ---------------------------------------------------- //

typedef enum GraphicsPipelineType {
    GRAPHICS_PIPELINE_TYPE_TEXTURED,
    GRAPHICS_PIPELINE_TYPE_SOLID_COLOUR,
    GRAPHICS_PIPELINE_TYPE_TRANSPARENT,
    GRAPHICS_PIPELINE_TYPE_WIREFRAME,

    NUM_GRAPHICS_PIPELINE
} GraphicsPipelineType;
